#!/bin/bash
#set -x 
echo "Arguments list:"
echo "\$1: Mesos master node number, default is 3"
echo "\$2: Zookeeper cluster, default is zoo1:2181,zoo2:2181,zoo3:2181"
echo "\$3: Ethernet interface which is used to communicate with the mesos on host, default is 'eth0'"
echo "\$4: Ethernet interface which is used to assign IP address on container, default is 'eth1'"

NODE_COUNT=${1:-3}
ZOO_CLUSTER=${2:-zoo1:2181,zoo2:2181,zoo3:2181}
HOST_INTERFACE=${3:-eth0}
CONTAINER_IF=${4:-eth1}
current_dir=$(pwd)

quorum=$(expr 1 + $NODE_COUNT / 2)
echo "quorum: $quorum"
local_ip="$(ifconfig $INTERFACE | grep 'inet ' | awk '{print $2}')"
for (( i=1; i<=$NODE_COUNT; i++ ))
do
  port1=$(expr 5049 + $i)
  sudo docker rm -f mesos_master_$i
  sudo ./pipework $HOST_INTERFACE -i $CONTAINER_IF $(docker run --restart=always -d \
    -e MESOS_WORK_DIR=/var/mesos \
    -e MESOS_LOG_DIR=/var/log \
    -e MESOS_ZK=zk://$ZOO_CLUSTER/mesos \
    -e MESOS_QUORUM=$quorum \
    -e MESOS_ZK_SESSION_TIMEOUT=30secs \
    -e MESOS_REGISTRY_STORE_TIMEOUT=15secs \
    -e MESOS_CLUSTER=Nalanda \
    -e CONTAINER_IF=$CONTAINER_IF \
    -p $port1:5050 --name mesos_master_$i mesos:0.0.1 \
    mesos-master) dhcp
done

# TODO enable docker SDN via macvlan or OVS
