#!/bin/bash
set -x 
echo "Arguments list:"
echo "\$1: Ethernet interface which is used to communicate with the spark on host, default is 'eth0'"
echo "\$2: Ethernet interface which is used to assign IP address on container, default is 'eth1'"
echo "\$3: Docker image name, default: spark:0.0.1"
echo "\$4: IP address of contatiner, default: dhcp"
echo "\$5: HDFS FS host, default: hdfsnamenode:8020"
echo "\$6: HDFS HTTP host, default: hdfsnamenode:50070"
echo "\$7: spark master, default: mesos://zk://zoo1:2181/mesos"
source ./utils

HOST_INTERFACE=${1:-eth0}
CONTAINER_IF=${2:-eth1}
IMAGE_NAME=${3:-spark:0.0.1}
CONTAINER_IP=${4:-dhcp}
HDFS_FS_HOST=${5:-hdfsnamenode:8020}
HDFS_HTTP_HOST=${6:-hdfsnamenode:50070}
SPARK_MASTER=${7:-mesos://zk://zoo1:2181/mesos}
current_dir=$(pwd)

script_prefix="spark"

local_ip="$(ifconfig $HOST_INTERFACE | grep 'inet ' | awk '{print $2}')"
container_name=${script_prefix}
sudo docker rm -f $container_name
sudo ./pipework $HOST_INTERFACE -i $CONTAINER_IF \
    $(docker run -d -t \
    -p 4040:4040 -p 42285:42285\
    -e CONTAINER_IF=$CONTAINER_IF \
    -e HDFS_FS_HOST=$HDFS_FS_HOST \
    -e HDFS_HTTP_HOST=$HDFS_HTTP_HOST \
    -e SPARK_MASTER=$SPARK_MASTER \
    --hostname=${CONTAINER_IP%%/*} \
    --name $container_name $IMAGE_NAME bash) $CONTAINER_IP

