#!/bin/bash
#set -x 
echo "Arguments list:"
echo "\$1: Mesos master node number, default is 3"
echo "\$2: Zookeeper cluster, default is zoo1:2181,zoo2:2181,zoo3:2181"
echo "\$3: Ethernet interface which is used to communicate with the mesos on host, default is 'eth0'"
echo "\$4: Ethernet interface which is used to assign IP address on container, default is 'eth1'"
echo "\$5: Docker image name, default: mesos:0.0.1"
echo "\$6: IP address of contatiner, default: dhcp"

source ./utils

NODE_COUNT=${1:-3}
ZOO_CLUSTER=${2:-zoo1:2181,zoo2:2181,zoo3:2181}
HOST_INTERFACE=${3:-eth0}
CONTAINER_IF=${4:-eth1}
IMAGE_NAME=${5:-mesos:0.0.1}
CONTAINER_IP=${6:-dhcp}

current_dir=$(pwd)

quorum=$(expr 1 + $NODE_COUNT / 2)
echo "quorum: $quorum"
local_ip="$(ifconfig $INTERFACE | grep 'inet ' | awk '{print $2}')"
for (( i=1; i<=$NODE_COUNT; i++ ))
do
  port1=$(expr 5049 + $i)
  SDN_IP=$(get_new_sdn_ip $CONTAINER_IP $i)
  echo "SDN_IP: $SDN_IP"
  sudo docker rm -f mesos_master_$i
  echo "CONTAINER_IF=$CONTAINER_IF
ZOO_CLUSTER=$ZOO_CLUSTER
quorum=$quorum
i=$i
IMAGE_NAME=$IMAGE_NAME
HOST_INTERFACE=$HOST_INTERFACE
SDN_IP=$SDN_IP" > mesos_master_${i}_temp.sh
  echo '
CONTAINER_ID=`sudo docker run -d \
    -e MESOS_WORK_DIR=/var/mesos \
    -e MESOS_LOG_DIR=/var/log \
    -e MESOS_ZK=zk://$ZOO_CLUSTER/mesos \
    -e MESOS_QUORUM=$quorum \
    -e MESOS_ZK_SESSION_TIMEOUT=30secs \
    -e MESOS_REGISTRY_STORE_TIMEOUT=15secs \
    -e MESOS_CLUSTER=Nalanda \
    -e MESOS_PORT=5050 \
    -e CONTAINER_IF=$CONTAINER_IF \
    --name mesos_master_$i $IMAGE_NAME \
    mesos-master` 
sudo ./pipework $HOST_INTERFACE -i $CONTAINER_IF \
    $CONTAINER_ID $SDN_IP' >> mesos_master_${i}_temp.sh
done

# Start docker container in parallel
ls mesos_master_*_temp.sh |xargs -P $NODE_COUNT -n 1 sh
rm -f mesos_master_*_temp.sh

